[tool.ruff]
# ignore = ["E203","E231","E261","E402","E501","E711","E712","E722","W605","E741"]
line-length = 80

[tool.ruff.lint]
select = ["E4", "E7", "E9", "F", "I"]

[tool.ruff.lint.isort]
known-first-party = ["test", "app"]
